[package]
name = "russimp"
version = "0.1.0"
authors = ["Jhonny Knaak de Vargas <jhonny.knaak@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
russimp-sys = { version = "0.1.0", path = "russimp-sys" }
num-derive = "0.3.3"
num-traits = "0.2.14"
derivative = "2.1.1"