[package]
name = "russimp"
version = "0.1.0"
authors = ["Jhonny Knaak de Vargas"]
edition = "2018"
license = "assimp"
readme = "README.md"
homepage = "https://github.com/jkvargas/russimp"
categories = ["rendering","external-ffi-bindings","game-engines","multimedia"]
keywords = ["assimp", "3d", "blend", "3ds", "obj", "glTF"]
repository = "https://github.com/jkvargas/russimp"
description = "Assimp bindings for rust"

[lib]
crate-type = ["dylib"]

[dependencies]
russimp-sys = { version = "0.1.0", path = "russimp-sys" }
num-derive = "0.3.3"
num-traits = "0.2.14"