name: russimp-sys
on: [push, pull_request]
jobs:
  # Run cargo test with default, no and all features.
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install llvm, clang and cmake
        run: apt install llvm clang cmake
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        run: cargo test --verbose
      - name: cargo test - no features
        run: cargo test --no-default-features --verbose
      - name: cargo test - all features
        run: cargo test --all-features --verbose